import { useEffect, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import axios from "axios";
import { Link, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";

const api = axios.create({ baseURL: "http://127.0.0.1:8000" });
type User = { id: string; email: string; full_name: string; role: string };
type Project = { id: string; owner_id: string; name: string; organism?: string; visibility: string };
type Dataset = { id: string; file_name: string; sequence_length: number | null; gc_content: number | null; status: string; created_at: string };

function currentUser(): User | null {
  const value = localStorage.getItem("genelab_user");
  return value ? JSON.parse(value) as User : null;
}

function AuthPage() {
  const navigate = useNavigate();
  const [loginMode, setLoginMode] = useState(true);
  const [form, setForm] = useState({ email: "", password: "", full_name: "" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError(""); setLoading(true);
    try {
      const { data } = await api.post(loginMode ? "/auth/login" : "/auth/register", loginMode ? { email: form.email, password: form.password } : form);
      localStorage.setItem("genelab_user", JSON.stringify(data.user)); localStorage.setItem("genelab_token", data.access_token); navigate("/dashboard");
    } catch (requestError) { setError(axios.isAxiosError(requestError) ? requestError.response?.data?.detail ?? "Could not connect to the API" : "Something went wrong"); } finally { setLoading(false); }
  };
  return <main className="auth-layout"><section className="auth-aside"><Link className="brand" to="/">GL<span>/</span></Link><p className="kicker">GENELAB / RESEARCH ACCESS</p><h1>Data,<br /><em>that</em><br />speaks.</h1><p>Enter your research workspace and continue working with DNA data.</p><div className="aside-code">ATG · CCG · GGA · TTA</div></section><section className="auth-panel"><div className="auth-panel-inner"><p className="kicker">{loginMode ? "WELCOME BACK" : "NEW RESEARCHER"}</p><h2>{loginMode ? "Welcome back" : "Create an account"}</h2><p className="muted">{loginMode ? "Sign in to your research workspace." : "Start building your data laboratory."}</p><form onSubmit={submit} className="form-stack">{!loginMode && <label>Full name<input required value={form.full_name} onChange={event => setForm({ ...form, full_name: event.target.value })} placeholder="Alex Morgan" /></label>}<label>Email<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} placeholder="you@university.edu" /></label><label>Password<input required type="password" minLength={loginMode ? 1 : 8} value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} placeholder="Enter your password" /></label>{error && <p className="form-error">{error}</p>}<button className="solid-button" disabled={loading}>{loading ? "Connecting..." : loginMode ? "Sign In to GeneLab →" : "Create Account →"}</button></form><button className="text-button" onClick={() => { setLoginMode(!loginMode); setError(""); }}>{loginMode ? "New here? Create an account" : "Already have an account? Sign in"}</button></div></section></main>;
}

function Shell({ children }: { children: ReactNode }) {
  const navigate = useNavigate(); const user = currentUser();
  const logout = () => { localStorage.removeItem("genelab_user"); localStorage.removeItem("genelab_token"); navigate("/auth"); };
  return <div className="workspace"><aside className="sidebar"><Link className="brand" to="/dashboard">GL<span>/</span></Link><p className="sidebar-label">Workspace</p><nav className="side-nav"><Link to="/dashboard">◈ <span>Projects</span></Link><Link to="/dashboard">⌁ <span>Datasets</span></Link><Link to="/dashboard">◌ <span>Analysis</span></Link></nav><div className="sidebar-bottom"><div className="user-chip"><span>{user?.full_name?.slice(0, 1).toUpperCase()}</span><div><strong>{user?.full_name ?? "Researcher"}</strong><small>{user?.email}</small></div></div><button className="logout-button" onClick={logout}>Sign Out</button></div></aside><div className="workspace-main"><header className="workspace-header"><span className="breadcrumb">GENELAB <b>/</b> WORKSPACE</span><span className="api-indicator"><i /> API connected</span></header>{children}</div></div>;
}

function Dashboard() {
  const user = currentUser(); const navigate = useNavigate(); const [projects, setProjects] = useState<Project[]>([]); const [showForm, setShowForm] = useState(false); const [name, setName] = useState(""); const [organism, setOrganism] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (user) api.get(`/projects?owner_id=${user.id}`).then(response => setProjects(response.data)).catch(() => undefined); }, [user]);
  const create = async (event: FormEvent) => { event.preventDefault(); try { const { data } = await api.post("/projects", { owner_id: user?.id, name, organism, visibility: "private" }); setProjects([...projects, data]); setName(""); setOrganism(""); setShowForm(false); } catch { setError("Could not create the project. Make sure the backend is running."); } };
  return <Shell><main className="content"><div className="content-heading"><div><p className="kicker">OVERVIEW / 01</p><h1>Your projects</h1><p className="muted">Keep your data together in one focused research workspace.</p></div><button className="solid-button compact" onClick={() => setShowForm(!showForm)}>+ Create Project</button></div>{showForm && <form className="inline-form" onSubmit={create}><input required value={name} onChange={event => setName(event.target.value)} placeholder="Project name" /><input value={organism} onChange={event => setOrganism(event.target.value)} placeholder="Organism, e.g. E. coli" /><button className="solid-button compact">Create →</button></form>}{error && <p className="form-error">{error}</p>}<div className="stats-row"><div><span>ACTIVE PROJECTS</span><strong>{projects.length.toString().padStart(2, "0")}</strong></div><div><span>DATASETS</span><strong>--</strong></div><div><span>ANALYSIS STATUS</span><strong className="status-text">READY</strong></div></div><div className="list-heading"><h2>Recent Projects</h2><span>{projects.length} total</span></div><div className="project-grid">{projects.map(project => <button className="project-tile" key={project.id} onClick={() => navigate(`/projects/${project.id}`)}><div className="tile-top"><span className="project-mark">DNA</span><span className="private-label">{project.visibility}</span></div><h3>{project.name}</h3><p>{project.organism || "Organism not specified"}</p><span className="tile-arrow">↗</span></button>)}{projects.length === 0 && <div className="empty-state"><span className="empty-icon">＋</span><h3>Your first study</h3><p>Create a project to upload FASTA data.</p><button className="text-button" onClick={() => setShowForm(true)}>Create Project →</button></div>}</div></main></Shell>;
}

function ProjectPage() {
  const { project_id } = useParams(); const [project, setProject] = useState<Project | null>(null); const [datasets, setDatasets] = useState<Dataset[]>([]); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!project_id) return; api.get(`/projects/${project_id}`).then(response => setProject(response.data)).catch(() => undefined); api.get(`/projects/${project_id}/datasets`).then(response => setDatasets(response.data)).catch(() => undefined); }, [project_id]);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !project_id) return; setUploading(true); setError(""); const body = new FormData(); body.append("file", file); try { const { data } = await api.post(`/projects/${project_id}/datasets`, body); setDatasets(current => [data, ...current]); } catch (requestError) { setError(axios.isAxiosError(requestError) ? requestError.response?.data?.detail ?? "Could not upload the file" : "Upload failed"); } finally { setUploading(false); event.target.value = ""; } };
  return <Shell><main className="content project-content"><Link className="back-link" to="/dashboard">← All Projects</Link><div className="project-title"><div><p className="kicker">PROJECT / {project_id?.slice(0, 8)}</p><h1>{project?.name ?? "DNA Study"}</h1><p className="muted">{project?.organism ?? "Research project"}</p></div><label className="upload-button"><input type="file" accept=".fasta" onChange={upload} disabled={uploading} />{uploading ? "Processing..." : "↑ Upload FASTA File"}</label></div><section className="upload-zone"><div className="upload-symbol">↑</div><div><h2>Add a sequence</h2><p>Choose a FASTA file from your device. Analysis starts automatically.</p></div><label className="outline-button">Choose File<input type="file" accept=".fasta" onChange={upload} disabled={uploading} /></label></section>{error && <p className="form-error">{error}</p>}<div className="list-heading results-heading"><div><p className="kicker">ANALYSIS OUTPUT</p><h2>Sequence Results</h2></div><span>{datasets.length} datasets</span></div><div className="results-table"><div className="table-head"><span>FILE</span><span>STATUS</span><span>LENGTH</span><span>GC CONTENT</span><span>DATE</span></div>{datasets.map(dataset => <div className="table-row" key={dataset.id}><strong>{dataset.file_name}</strong><span className={`dataset-status ${dataset.status}`}>{dataset.status}</span><span>{dataset.sequence_length?.toLocaleString() ?? "—"}</span><span className="gc-value">{dataset.gc_content !== null ? `${dataset.gc_content.toFixed(2)}%` : "—"}</span><span>{new Date(dataset.created_at).toLocaleDateString("en-US")}</span></div>)}{datasets.length === 0 && <div className="table-empty">Your sequence results will appear here after the first FASTA upload.</div>}</div></main></Shell>;
}

export default function App() { return <Routes><Route path="/" element={<Navigate to={currentUser() ? "/dashboard" : "/auth"} replace />} /><Route path="/auth" element={<AuthPage />} /><Route path="/dashboard" element={currentUser() ? <Dashboard /> : <Navigate to="/auth" replace />} /><Route path="/projects/:project_id" element={currentUser() ? <ProjectPage /> : <Navigate to="/auth" replace />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
